
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 17 21:23:06 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 32;
  public static final int JEDNAKOJEDNAKO = 16;
  public static final int PROCENAT = 38;
  public static final int CONST = 14;
  public static final int ZAREZ = 24;
  public static final int NUMCONST = 41;
  public static final int LPAREN = 26;
  public static final int CONTINUE = 12;
  public static final int VECEJEDNAKO = 19;
  public static final int MINUS = 35;
  public static final int RPAREN = 27;
  public static final int AND = 40;
  public static final int PODELJENO = 37;
  public static final int OR = 39;
  public static final int JEDNAKO = 15;
  public static final int MANJEJEDNAKO = 21;
  public static final int PLUS = 34;
  public static final int IF = 8;
  public static final int RUGLASTA = 31;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 33;
  public static final int RETURN = 4;
  public static final int NIJEJEDNAKO = 17;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int SLEDI = 22;
  public static final int TACZAR = 23;
  public static final int IDENT = 42;
  public static final int BREAK = 11;
  public static final int VOID = 5;
  public static final int FOREACH = 13;
  public static final int MANJE = 20;
  public static final int LBRACE = 28;
  public static final int ELSE = 9;
  public static final int VECE = 18;
  public static final int READ = 6;
  public static final int CHARCONST = 43;
  public static final int WHILE = 10;
  public static final int TACKA = 25;
  public static final int RBRACE = 29;
  public static final int BOOLCONST = 44;
  public static final int PROG = 2;
  public static final int PUTA = 36;
  public static final int LUGLASTA = 30;
  public static final int PRINT = 3;
}

