
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int PROG = 1;
  public static final int PRINT = 2;
  public static final int RETURN = 3;
  public static final int VOID = 4;
  public static final int READ = 5;
  public static final int NEW = 6;
  public static final int IF = 7;
  public static final int ELSE = 8;
  public static final int WHILE = 9;
  public static final int BREAK = 10;
  public static final int CONTINUE = 11;
  public static final int FOREACH = 12;
  public static final int CONST = 13;
  
  public static final int JEDNAKO = 14;
  public static final int JEDNAKOJEDNAKO = 15;
  public static final int NIJEJEDNAKO = 16;
  public static final int VECE = 17;
  public static final int VECEJEDNAKO = 18;
  public static final int MANJE = 19;
  public static final int MANJEJEDNAKO = 20;
  
  public static final int TACZAR = 21;
  public static final int ZAREZ = 22;
  public static final int DVOTACKA = 23;
  public static final int TACKA = 24;
  
  public static final int LPAREN = 25;
  public static final int RPAREN = 26;
  public static final int LBRACE = 27;
  public static final int RBRACE = 28;
  public static final int LUGLASTA = 29;
  public static final int RUGLASTA = 30;
  
  public static final int PLUSPLUS = 31;
  public static final int MINUSMINUS = 32;
  public static final int PLUS = 33;
  public static final int MINUS = 34;
  public static final int PUTA = 35;
  public static final int PODELJENO = 36;
  public static final int PROCENAT = 37;
  
  public static final int OR = 38;
  public static final int AND = 39;
  
  public static final int BOOLCONST = 40;
  public static final int NUMCONST = 41;
  public static final int IDENT = 42;
  public static final int CHARCONST = 43;
  public static final int SLEDI = 44;
  
  public static final int EOF = 45;
  
  
  
  
  
  
}

